### ISSUE TITLE
Edges Flip 180 when moving nodes.

### ISSUE THREAD

**Issue by lennonc1atwit** [SkywalkerDarren/flutter_force_directed_graph#6]
Edges Flip 180 degrees when passing the X axis of separation for nodes. Moving 1 node past another, it shares an edge with, on the x axis results in the edge widget flipping 180 degrees.

**Comment by SkywalkerDarren** [comment]
In the `ForceDirectedGraphWidget`, there is a property called `edgeAlwaysUp`, which has a default value of true. You can try changing this value to see if it meets your requirements.

**Comment by lennonc1atwit** [comment]
Thank you for the quick reply, on my 1.0.6 version there is no property edgeAlwaysUp but looking at the repo i can see it just swaps edge.angle for edge.rawAngle so i did this manually and it works now. any idea why github and the package are different?

**Comment by SkywalkerDarren** [comment]
v1.0.7 has been released.
